//! Lifted enum types (`E0`–`E16`) used as [`TypeSet::Enum`] and [`TypeSet::EnumRef`] associated types.
//!
//! Each `EN<T1, …, TN>` is an anonymous enum with exactly N variants — one per type parameter.
//! They are the *runtime storage* inside a [`OneOf`]: a `OneOf<(A, B, C)>` stores its value
//! as an `E3<A, B, C>`.
//!
//! These types are generated by macro and are an implementation detail; prefer working with
//! [`OneOf`] directly. You can obtain the underlying enum via [`OneOf::to_enum`] or
//! [`OneOf::as_enum`] for exhaustive pattern matching.
//!
//! [`TypeSet::Enum`]: crate::TypeSet::Enum
//! [`TypeSet::EnumRef`]: crate::TypeSet::EnumRef
//! [`OneOf`]: crate::OneOf
//! [`OneOf::to_enum`]: crate::OneOf::to_enum
//! [`OneOf::as_enum`]: crate::OneOf::as_enum

macro_rules! define_lifted_enum {
    ($enum:ident; $($ty:ident),+ $(,)?) => {
        #[doc = concat!(
            "Lifted runtime enum for a `OneOf` over `(",
            $(stringify!($ty), ", ",)+
            ")`.",
        )]
        pub enum $enum<$($ty),+> {
            $(
                #[doc = concat!("Variant holding a `", stringify!($ty), "` value.")]
                $ty($ty),
            )+
        }
    };
}

/// The lifted enum for [`OneOf<()>`](crate::OneOf) — uninhabited, mirrors [`End`](crate::End).
///
/// `E0` has no variants and can never be constructed. It is the `TypeSet::Enum` for the
/// empty type set `()`, meaning a `OneOf<()>` can also never be constructed.
pub enum E0 {}

macro_rules! define_supported_lifted_enums {
    (each: $($enum:ident => $($ty:ident),+;)+) => {
        $(
            define_lifted_enum!($enum; $($ty),+);
        )+
    };
}

crate::with_supported_type_sets!(define_supported_lifted_enums);

impl<T1> From<T1> for E1<T1> {
    fn from(t1: T1) -> E1<T1> {
        E1::T1(t1)
    }
}

/* ------------------------- Enum conversions ----------------------- */

macro_rules! impl_one_of_to_enum {
    ($enum:ident; $($ty:ident),+ $(,)?) => {
        impl<$($ty),+> From<$crate::OneOf<($($ty,)+)>> for $enum<$($ty),+>
        {
            fn from(one_of: $crate::OneOf<($($ty,)+)>) -> Self {
                one_of.value
            }
        }

        impl<'a, $($ty),+> From<&'a $crate::OneOf<($($ty,)+)>> for $enum<$(&'a $ty),+>
        {
            fn from(one_of: &'a $crate::OneOf<($($ty,)+)>) -> Self {
                match &one_of.value {
                    $(
                        $enum::$ty(value) => $enum::$ty(value),
                    )+
                }
            }
        }
    };
}

macro_rules! impl_supported_one_of_to_enum {
    (each: $($enum:ident => $($ty:ident),+;)+) => {
        $(
            impl_one_of_to_enum!($enum; $($ty),+);
        )+
    };
}

crate::with_supported_type_sets!(impl_supported_one_of_to_enum);
