//! Lifted enum types (`E0`–`E16`) used as [`TypeSet::Enum`] and [`TypeSet::EnumRef`] associated types.
//!
//! Each `EN<T1, …, TN>` is an anonymous enum with exactly N variants — one per type parameter.
//! They are the *runtime storage* inside a [`OneOf`]: a `OneOf<(A, B, C)>` stores its value
//! as an `E3<A, B, C>`.
//!
//! These types are generated by macro and are an implementation detail; prefer working with
//! [`OneOf`] directly. You can obtain the underlying enum via [`OneOf::to_enum`] or
//! [`OneOf::as_enum`] for exhaustive pattern matching.
//!
//! [`TypeSet::Enum`]: crate::TypeSet::Enum
//! [`TypeSet::EnumRef`]: crate::TypeSet::EnumRef
//! [`OneOf`]: crate::OneOf
//! [`OneOf::to_enum`]: crate::OneOf::to_enum
//! [`OneOf::as_enum`]: crate::OneOf::as_enum

macro_rules! define_lifted_enum {
    ($enum:ident; $($ty:ident),+ $(,)?) => {
        #[doc = concat!(
            "Lifted runtime enum for a `OneOf` over `(",
            $(stringify!($ty), ", ",)+
            ")`.",
        )]
        pub enum $enum<$($ty),+> {
            $(
                #[doc = concat!("Variant holding a `", stringify!($ty), "` value.")]
                $ty($ty),
            )+
        }

        impl<$($ty: core::fmt::Debug),+> core::fmt::Debug for $enum<$($ty),+> {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                match self {
                    $($enum::$ty(v) => core::fmt::Debug::fmt(v, f),)+
                }
            }
        }

        impl<$($ty: core::fmt::Display),+> core::fmt::Display for $enum<$($ty),+> {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                match self {
                    $($enum::$ty(v) => core::fmt::Display::fmt(v, f),)+
                }
            }
        }

        impl<$($ty: core::clone::Clone),+> core::clone::Clone for $enum<$($ty),+> {
            fn clone(&self) -> Self {
                match self {
                    $($enum::$ty(v) => $enum::$ty(core::clone::Clone::clone(v)),)+
                }
            }
        }

        impl<$($ty: core::error::Error + 'static),+> core::error::Error for $enum<$($ty),+> {
            fn source(&self) -> Option<&(dyn core::error::Error + 'static)> {
                match self {
                    $($enum::$ty(v) => v.source(),)+
                }
            }

            #[cfg(feature = "error_provide")]
            fn provide<'a>(&'a self, request: &mut core::error::Request<'a>) {
                match self {
                    $($enum::$ty(v) => core::error::Error::provide(v, request),)+
                }
            }
        }
    };
}

/// The lifted enum for [`OneOf<()>`](crate::OneOf) — uninhabited, mirrors [`End`](crate::End).
///
/// `E0` has no variants and can never be constructed. It is the `TypeSet::Enum` for the
/// empty type set `()`, meaning a `OneOf<()>` can also never be constructed.
pub enum E0 {}

impl core::fmt::Debug for E0 {
    fn fmt(&self, _: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        unreachable!()
    }
}

impl core::fmt::Display for E0 {
    fn fmt(&self, _: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        unreachable!()
    }
}

impl core::clone::Clone for E0 {
    fn clone(&self) -> Self {
        unreachable!()
    }
}

impl core::error::Error for E0 {
    fn source(&self) -> Option<&(dyn core::error::Error + 'static)> {
        unreachable!()
    }
}

macro_rules! define_supported_lifted_enums {
    (each: $($enum:ident => $($ty:ident),+;)+) => {
        $(
            define_lifted_enum!($enum; $($ty),+);
        )+
    };
}

crate::with_supported_type_sets!(define_supported_lifted_enums);

impl<T1> From<T1> for E1<T1> {
    #[inline]
    fn from(t1: T1) -> Self {
        Self::T1(t1)
    }
}

/* ------------------------- Enum conversions ----------------------- */

macro_rules! impl_one_of_to_enum {
    ($enum:ident; $($ty:ident),+ $(,)?) => {
        impl<$($ty),+> From<$crate::OneOf<($($ty,)+)>> for $enum<$($ty),+>
        {
            #[inline]
            fn from(one_of: $crate::OneOf<($($ty,)+)>) -> Self {
                one_of.value
            }
        }

        impl<'a, $($ty),+> From<&'a $crate::OneOf<($($ty,)+)>> for $enum<$(&'a $ty),+>
        {
            #[inline]
            fn from(one_of: &'a $crate::OneOf<($($ty,)+)>) -> Self {
                match &one_of.value {
                    $(
                        $enum::$ty(value) => $enum::$ty(value),
                    )+
                }
            }
        }
    };
}

macro_rules! impl_supported_one_of_to_enum {
    (each: $($enum:ident => $($ty:ident),+;)+) => {
        $(
            impl_one_of_to_enum!($enum; $($ty),+);
        )+
    };
}

crate::with_supported_type_sets!(impl_supported_one_of_to_enum);
